controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
add_capsule:
    path: /{id}/add_capsule
    controller: App\Controller\CapsuleController::addCapsule
profile_index:
    path: /{slug}
    controller: App\Controller\ProfileController::index
profile_add_capsule:
    path: /{id}/profile_add_capsule
    controller: App\Controller\ProfileController::addCapsule
app_capsule_delete:
  path: /{slug}/{id}/delete-capsule
  controller: App\Controller\CapsuleController::deleteCapsule
capsule_index:
    path: /{slug_user}/{slug_capsule}
    controller: App\Controller\CapsuleController::index
user_capsule_list:
    path: /ajax_request
    defaults: { _controller: App\Controller\CapsuleController::index }


